export const knowledgeSentences = [
  "Layout is where the browser figures out the geometric information for elements: their size and location in the page.",
  "Each element will have explicit or implicit sizing information based on the CSS that was used, the contents of the element, or a parent element.",
  "The process is called Layout in Chrome and derived browsers such as Edge, and Safari.",
  "In Firefox it's called Reflow, but the process is effectively the same.",
  "The immediate concerns for layout cost are the number of elements that require layout, which is a byproduct of the page's DOM size.",
  "The complexity of those layouts is also a concern.",
  "Layout has a direct effect on interaction latency.",
  "Layout is normally scoped to the whole document.",
  "The number of DOM elements will affect performance; you should avoid triggering layout wherever possible.",
  "You should avoid forced synchronous layouts and layout thrashing; read style values then make style changes.",
  "When a user interacts with the page, those interactions should be as fast as possible.",
  "The amount of time it takes for an interaction to complete is known as interaction latency.",
  "Visual updates can involve some amount of layout work in order to achieve that goal.",
  "In order to keep your website's INP as low as possible, it's important to avoid layout when possible.",
  "Changes to geometric properties, such as width, height, left, or top all require layout.",
  "If you have a lot of elements, it's going to take a long time to figure out the locations and dimensions of them all.",
  "It is, however, possible to force a browser to perform layout earlier with JavaScript.",
  "This is called forced synchronous layout or sometimes forced reflow.",
  "You should always batch your style reads and do them first and then do any writes.",
  "There's a way to make forced synchronous layouts even worse: do lots of them in quick succession.",
  "DevTools has a Forced Reflow insight, to help you quickly identify cases of forced synchronous layouts.",
];
